# Generated by Django 3.0.8 on 2020-07-27 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_auto_20200727_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='is_expired',
        ),
        migrations.AlterField(
            model_name='flight',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
