# Generated by Django 3.0.8 on 2020-07-27 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20200727_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flight',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
