# Generated by Django 3.0.8 on 2020-07-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_auto_20200730_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='seats',
            field=models.IntegerField(blank=True),
        ),
    ]
