# Generated by Django 3.0.8 on 2020-08-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_auto_20200730_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
