# Generated by Django 3.0.8 on 2020-08-14 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_flight_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='added_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
